[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm install --prefer-offline --no-audit --no-fund --loglevel=error"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"