[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules/.cache && npm install --prefer-offline --no-audit --no-fund --loglevel=error && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3