[build]
builder = "nixpacks"
buildCommand = "npm install --force && npm run build"
watchPatterns = ["/frontend/**"]

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_NO_CACHE = "1"
NODE_ENV = "production"