[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install --force --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NIXPACKS_NO_CACHE = "1"