[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install --production=false && npm run build"

[deploy]
startCommand = "cd frontend && npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10