#!/bin/bash

echo "🚀 Backend Railway 배포 가이드"
echo "=================================="
echo ""
echo "Railway에서 Backend를 별도 서비스로 배포하는 방법:"
echo ""
echo "1. Railway Dashboard 접속 (https://railway.app)"
echo ""
echo "2. 새 서비스 생성:"
echo "   - 'New Service' 클릭"
echo "   - 'Deploy from GitHub repo' 선택"
echo "   - 'mylife-cinema-' 저장소 선택"
echo ""
echo "3. Root Directory 설정 (중요!):"
echo "   - Settings 탭으로 이동"
echo "   - 'Root Directory' 필드에 'backend' 입력"
echo "   - Save 클릭"
echo ""
echo "4. 환경변수 설정:"
echo "   - Variables 탭으로 이동"
echo "   - 다음 변수들 추가:"
echo ""
echo "   PORT=8000"
echo "   NODE_ENV=production"
echo "   FRONTEND_URL=https://www.lifecinema.site"
echo ""
echo "5. Deploy 탭에서 배포 상태 확인"
echo ""
echo "6. 배포 완료 후 생성된 URL 복사"
echo "   예: https://mylife-cinema-backend-production.up.railway.app"
echo ""
echo "=================================="
echo ""
echo "⚠️  중요: Backend 서비스는 Frontend와 별도로 생성해야 합니다!"
echo ""