[build]
builder = "nixpacks"
buildCommand = "npm install --production=false && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10